version: "3"
services: 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8090:80
    volumes: 
      - ./:/app
      - ${GOPATH}/pkg/mod:/go/pkg/mod
    depends_on: 
      - postgres
      - redis

  postgres:
    image: postgres
    environment: 
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: auth
    ports: 
      - 5432:5432
    volumes: 
      - ./resources/db:/docker-entrypoint-initdb.d
      - ./var/docker/postgres/data:/var/lib/postgresql/data

  redis:
    image: redis
    environment: 
      ALLOW_EMPTY_PASSWORD: "yes"
    volumes: 
      - ./var/docker/redis/data:/bitnami/data
